services:
  - type: web
    name: inc-voting-system
    runtime: node
    plan: free
    buildCommand: npm ci && npm --prefix inc-voting-ui ci && npm --prefix inc-voting-ui run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
